### ISSUE TITLE
OWHyper: crash on change of input domain

### ISSUE THREAD

**Issue by stuart-cls** [Quasars/orange-spectroscopy#199]
Steps to reproduce:

1. Load file
2. Integrate spectra
  a. Select peak area, for example
  b. Auto-commit = False
  c. Output as metas = True
  d. Press commit
3. HyperSpectra
  a. Use feature: select peak area feature you created
4. Go back to Integrate Spectra, change Output as metas to False

Gives this crash:

```
Exception:
ValueError: Combo box does not contain item ContinuousVariable(name='1807.624707383192 - 2137.5412614276593', number_of_decimals=3, compute_value=<orangecontrib.spectroscopy.preprocess.integrate.IntegrateFeatureSimple object at 0x0000018C01F61080>)
Module:
Orange.widgets.gui:2482
Widget Name:
HyperSpectra
Widget Module:
orangecontrib.spectroscopy.widgets.owhyper:886
Version:
3.15.0
Environment:
Python 3.6.6 on Windows 10 10.0.16299 AMD64
Installed Packages:
AnyQt==0.0.8, Bottleneck==1.2.1, CommonMark==0.7.5, Orange-Spectroscopy==0.3.7, Orange3==3.15.0, PySocks==1.6.8, asn1crypto==0.24.0, certifi==2018.4.16, cffi==1.11.5, chardet==3.0.4, colorcet==0.9.1, cryptography==2.2.2, decorator==4.3.0, dill==0.2.8.2, docutils==0.14, future==0.16.0, h5py==2.7.1, idna==2.7, joblib==0.12.1, keyring==9.0, keyrings.alt==3.1, mkl-fft==1.0.4, mkl-random==1.0.1, networkx==2.1, numpy==1.13.3, opusFC==1.1.1, pip==10.0.1, pyOpenSSL==18.0.0, pycparser==2.18, pyqtgraph==0.10.0, pyreadline==2.1, python-louvain==0.11, pywin32==223, requests==2.19.1, scikit-learn==0.19.1, scipy==0.19.1, serverfiles==0.2.1, setuptools==39.2.0, six==1.11.0, spectral==0.19, urllib3==1.23, wheel==0.31.1, win-inet-pton==1.0.1, wincertstore==0.2, xlrd==1.1.0
Machine ID:
109952947833691
Stack Trace:
Traceback (most recent call last):
  File "C:\Users\reads\AppData\Local\Orange\lib\site-packages\Orange\canvas\scheme\widgetsscheme.py", line 962, in process_signals_for_widget
    handler(*args)
  File "C:\Users\reads\AppData\Local\Orange\lib\site-packages\orangecontrib\spectroscopy\widgets\owhyper.py", line 886, in set_data
    self.openContext(data)
  File "C:\Users\reads\AppData\Local\Orange\lib\site-packages\Orange\widgets\widget.py", line 673, in openContext
    self.settingsHandler.open_context(self, *a)
  File "C:\Users\reads\AppData\Local\Orange\lib\site-packages\Orange\widgets\settings.py", line 926, in open_context
    super().open_context(widget, domain, *self.encode_domain(domain))
  File "C:\Users\reads\AppData\Local\Orange\lib\site-packages\Orange\widgets\settings.py", line 689, in open_context
    self.settings_to_widget(widget, *args)
  File "C:\Users\reads\AppData\Local\Orange\lib\site-packages\Orange\widgets\settings.py", line 961, in settings_to_widget
    setattr(instance, setting.name, value)
  File "C:\Users\reads\AppData\Local\Orange\lib\site-packages\Orange\widgets\gui.py", line 185, in __setattr__
    callback(value)
  File "C:\Users\reads\AppData\Local\Orange\lib\site-packages\Orange\widgets\gui.py", line 2407, in __call__
    self.action(*args)
  File "C:\Users\reads\AppData\Local\Orange\lib\site-packages\Orange\widgets\gui.py", line 2482, in action
    raise ValueError("Combo box does not contain item " + repr(value))
ValueError: Combo box does not contain item ContinuousVariable(name='1807.624707383192 - 2137.5412614276593', number_of_decimals=3, compute_value=<orangecontrib.spectroscopy.preprocess.integrate.IntegrateFeatureSimple object at 0x0000018C01F61080>)

Local Variables:
OrderedDict([('self',
              <Orange.widgets.gui.CallFrontComboBoxModel object at 0x0000018C00D4CBE0>),
             ('value',
              ContinuousVariable(name='1807.624707383192 - 2137.5412614276593', number_of_decimals=3, compute_value=<orangecontrib.spectroscopy.preprocess.integrate.IntegrateFeatureSimple object at 0x0000018C01F61080>))])
```

**Comment by stuart-cls** [comment]
The steps to reproduce above no longer do so in the current versions (Orange 3.20.1 and spec master) but I have a user getting this same crash when opening older workflows in the latest (3.20.1, 0.4.2). It seems to be due to Select Columns not restoring the selections on upgrade and then OWHyper not noticing the domain has changed, but I'm having trouble narrowing it down further.

**Comment by stuart-cls** [comment]
Ran into this again with a user opening an old workflow, but I still can't reproduce it in a small example. I think this is fixed with all the new DomainContextHandler stuff in 3.25 so I'm going to close this issue. If it comes back again, we can re-open.
