### ISSUE TITLE
README.pypi not packaged

### ISSUE THREAD

**Issue by tschoonj** [Quasars/orange-spectroscopy#229]
This is causing any `python setup.py install` build to fail when using the tarball uploaded to PyPI...

```
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-adrdj660/setup.py", line 15, in <module>
        LONG_DESCRIPTION = open(README_FILE).read()
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-adrdj660/README.pypi'
```

**Comment by markotoplak** [comment]
Thank you! I think it should be fixed now, but only in 0.3.11.

If you need to use the older version, please replace the problematic line with `LONG_DESCRIPTION = ""`


I do not understand why it disappeared - it was still there in 0.3.5. Perhaps different python libraries on packaging computers?

**Comment by tschoonj** [comment]
I can confirm that it works now. Many thanks!
