### ISSUE TITLE
Spectra: more robust handling of data changes

### ISSUE THREAD

**Issue by stuart-cls** [Quasars/orange-spectroscopy#234]
Steps to reproduce:
 - Using collagen dataset, Average Spectra by "type" 
 - connect the output to Spectra
 - Ensure "Show averages" is True, and Color by is "type"
 - Change the Average Spectra to average by "None" (disable averaging by group

You get the below crash. I think this is a bug in the Spectra widget and not the output of Average Spectra, but I could be wrong

Exception:
IndexError: boolean index did not match indexed array along dimension 1; dimension is 234 but corresponding boolean dimension is 1
Module:
orangecontrib.spectroscopy.widgets.owspectra:1200
Widget Name:
Spectra
Widget Module:
orangecontrib.spectroscopy.widgets.owspectra:1351
Version:
3.18.0.dev0+f9a1ad0
Environment:
Python 3.6.6 on Windows 10 10.0.16299 AMD64
Installed Packages:
AnyQt==0.0.8, Bottleneck==1.2.1, CommonMark==0.7.5, Orange-Spectroscopy==0.3.11, Orange3-Network==1.3.2, Orange3-Prototypes==0.10.2, Orange3==3.18.0.dev0+f9a1ad0, PySocks==1.6.8, Pygments==2.2.0, asn1crypto==0.24.0, backcall==0.1.0, beautifulsoup4==4.6.1, certifi==2018.4.16, cffi==1.11.5, chardet==3.0.4, colorama==0.3.9, colorcet==0.9.1, cryptography==2.2.2, cycler==0.10.0, decorator==4.3.0, dill==0.2.8.2, docutils==0.14, entrypoints==0.2.3, future==0.16.0, h5py==2.8.0, idna==2.7, ipython-genutils==0.2.0, ipython==6.5.0, jedi==0.12.1, joblib==0.12.1, jsonschema==2.6.0, jupyter-core==4.4.0, keyring==13.2.1, keyrings.alt==3.1, kiwisolver==1.0.1, matplotlib==3.0.1, mkl-fft==1.0.4, mkl-random==1.0.1, nbformat==4.4.0, networkx==2.1, numpy==1.15.0, opusFC==1.1.1, pandas==0.23.3, parso==0.3.1, pickleshare==0.7.4, pip==10.0.1, plotly==3.1.0, prompt-toolkit==1.0.15, pyOpenSSL==18.0.0, pycparser==2.18, pyparsing==2.3.0, pyqtgraph==0.10.0, pyreadline==2.1, python-dateutil==2.7.3, python-louvain==0.11, pytz==2018.5, pywin32==223, requests==2.19.1, retrying==1.3.3, scikit-learn==0.20.0, scipy==1.1.0, serverfiles==0.2.1, setuptools==39.2.0, simplegeneric==0.8.1, six==1.11.0, spectral==0.19, traitlets==4.3.2, urllib3==1.23, wcwidth==0.1.7, wheel==0.31.1, win-inet-pton==1.0.1, wincertstore==0.2, xlrd==1.1.0

Stack Trace:
Traceback (most recent call last):
  File "h:\src\orange3\Orange\canvas\scheme\widgetsscheme.py", line 1083, in process_signals_for_widget
    widget.handleNewSignals()
  File "H:\src\orange-spectroscopy\orangecontrib\spectroscopy\widgets\owspectra.py", line 1351, in handleNewSignals
    self.curveplot.update_view()
  File "H:\src\orange-spectroscopy\orangecontrib\spectroscopy\widgets\owspectra.py", line 1220, in update_view
    self.show_average()
  File "H:\src\orange-spectroscopy\orangecontrib\spectroscopy\widgets\owspectra.py", line 1200, in show_average
    ys = self.data.X[part_selection]
IndexError: boolean index did not match indexed array along dimension 1; dimension is 234 but corresponding boolean dimension is 1

Local Variables:
OrderedDict([('cinfo', []),
             ('colorv', None),
             ('dsplit', {None: array([[ True]])}),
             ('indices', array([[ True]])),
             ('part', None),
             ('part_selection', array([[ True]])),
             ('pen',
              defaultdict(<function CurvePlot.__init__.<locals>.<lambda> at 0x000001DD246DA378>,
                          {'DNA': <PyQt5.QtGui.QPen object at 0x000001DD24390CF8>,
                           'collagen': <PyQt5.QtGui.QPen object at 0x000001DD243CD908>,
                           'glycogen': <PyQt5.QtGui.QPen object at 0x000001DD24708F98>,
                           'lipids': <PyQt5.QtGui.QPen object at 0x000001DD25649438>})),
             ('self',
              <orangecontrib.spectroscopy.widgets.owspectra.CurvePlot object at 0x000001DD24654048>),
             ('x',
              array([ 902.5606,  906.4177,  910.2748,  914.1319,  917.989 ,  921.8461,
        925.7032,  929.5602,  933.4174,  937.2745,  941.1315,  944.9886,
        948.8458,  952.7028,  956.5599,  960.4171,  964.2741,  968.1312,
        971.9883,  975.8454,  979.7025,  983.5596,  987.4167,  991.2738,
        995.1309,  998.988 , 1002.845 , 1006.702 , 1010.559 , 1014.416 ,
       1018.273 , 1022.131 , 1025.988 , 1029.845 , 1033.702 , 1037.559 ,
       1041.416 , 1045.273 , 1049.13  , 1052.987 , 1056.844 , 1060.702 ,
       1064.559 , 1068.416 , 1072.273 , 1076.13  , 1079.987 , 1083.844 ,
       1087.701 , 1091.558 , 1095.415 , 1099.272 , 1103.13  , 1106.987 ,
       1110.844 , 1114.701 , 1118.558 , 1122.415 , 1126.272 , 1130.129 ,
       1133.986 , 1137.844 , 1141.701 , 1145.558 , 1149.415 , 1153.272 ,
       1157.129 , 1160.986 , 1164.843 , 1168.7   , 1172.557 , 1176.414 ,
       1180.271 , 1184.129 , 1187.986 , 1191.843 , 1195.7   , 1199.557 ,
       1203.414 , 1207.271 , 1211.128 , 1214.985 , 1218.843 , 1222.7   ,
       1226.557 , 1230.414 , 1234.271 , 1238.128 , 1241.985 , 1245.842 ,
       1249.699 , 1253.556 , 1257.413 , 1261.271 , 1265.128 , 1268.985 ,
       1272.842 , 1276.699 , 1280.556 , 1284.413 , 1288.27  , 1292.127 ,
       1295.984 , 1299.842 , 1303.699 , 1307.556 , 1311.413 , 1315.27  ,
       1319.127 , 1322.984 , 1326.841 , 1330.698 , 1334.555 , 1338.412 ,
       1342.27  , 1346.127 , 1349.984 , 1353.841 , 1357.698 , 1361.555 ,
       1365.412 , 1369.269 , 1373.126 , 1376.983 , 1380.841 , 1384.698 ,
       1388.555 , 1392.412 , 1396.269 , 1400.126 , 1403.983 , 1407.84  ,
       1411.697 , 1415.554 , 1419.411 , 1423.269 , 1427.126 , 1430.983 ,
       1434.84  , 1438.697 , 1442.554 , 1446.411 , 1450.268 , 1454.125 ,
       1457.982 , 1461.84  , 1465.697 , 1469.554 , 1473.411 , 1477.268 ,
       1481.125 , 1484.982 , 1488.839 , 1492.696 , 1496.553 , 1500.411 ,
       1504.268 , 1508.125 , 1511.982 , 1515.839 , 1519.696 , 1523.553 ,
       1527.41  , 1531.267 , 1535.124 , 1538.981 , 1542.839 , 1546.696 ,
       1550.553 , 1554.41  , 1558.267 , 1562.124 , 1565.981 , 1569.838 ,
       1573.695 , 1577.552 , 1581.41  , 1585.267 , 1589.124 , 1592.981 ,
       1596.838 , 1600.695 , 1604.552 , 1608.409 , 1612.266 , 1616.123 ,
       1619.98  , 1623.838 , 1627.695 , 1631.552 , 1635.409 , 1639.266 ,
       1643.123 , 1646.98  , 1650.837 , 1654.694 , 1658.551 , 1662.409 ,
       1666.266 , 1670.123 , 1673.98  , 1677.837 , 1681.694 , 1685.551 ,
       1689.408 , 1693.265 , 1697.122 , 1700.979 , 1704.837 , 1708.694 ,
       1712.551 , 1716.408 , 1720.265 , 1724.122 , 1727.979 , 1731.836 ,
       1735.693 , 1739.55  , 1743.408 , 1747.265 , 1751.122 , 1754.979 ,
       1758.836 , 1762.693 , 1766.55  , 1770.407 , 1774.264 , 1778.121 ,
       1781.979 , 1785.836 , 1789.693 , 1793.55  , 1797.407 , 1801.264 ])),
             ('ysall', [])])

**Comment by stuart-cls** [comment]
Hmm, this also happens if you use Scatterplot with Average Spectra from #233
