### ISSUE TITLE
PTIR reader problem from command line

### ISSUE THREAD

**Issue by borondics** [Quasars/orange-spectroscopy#508]
I get the following problem when trying to load a .ptir file in the command line version of Orange Spectroscopy.
 file 

The [file: single beam 100IR 10Green fast.ptir.zip](https://github.com/Quasars/orange-spectroscopy/files/5745189/single.beam.100IR.10Green.fast.ptir.zip) was a non-averaged series of spectra on the same point. 

I could load it without any problem in the GUI. I could also load another .ptir file in the CLI, so it might be an issue with this specific type of data collection mode.

@AustinTisor, @markotoplak what do you think?

```
Python 3.7.9 (default, Nov 14 2020, 23:05:21) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.19.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import Orange

In [2]: from orangecontrib.spectroscopy import data

In [3]: d = Orange.data.Table('single beam 100IR 10Green fast.ptir')
/Users/borondics/Documents/code/Python/orange-spectroscopy/orangecontrib/spectroscopy/data.py:1391: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  intensities = np.array(intensities)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
TypeError: only size-1 arrays can be converted to Python scalars

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
<ipython-input-3-158c415edc36> in <module>
----> 1 d = Orange.data.Table('single beam 100IR 10Green fast.ptir')

~/Documents/code/Python/orange3/Orange/data/table.py in __new__(cls, *args, **kwargs)
    239                 return cls.from_url(args[0], **kwargs)
    240             else:
--> 241                 return cls.from_file(args[0], **kwargs)
    242 
    243         elif isinstance(args[0], Table):

~/Documents/code/Python/orange3/Orange/data/table.py in from_file(cls, filename, sheet)
    691         reader = FileFormat.get_reader(absolute_filename)
    692         reader.select_sheet(sheet)
--> 693         data = reader.read()
    694 
    695         # Readers return plain table. Make sure to cast it to appropriate

~/Documents/code/Python/orange-spectroscopy/orangecontrib/spectroscopy/data.py in read(self)
     37 
     38     def read(self):
---> 39         return build_spec_table(*self.read_spectra())
     40 
     41 

~/Documents/code/Python/orange-spectroscopy/orangecontrib/spectroscopy/data.py in build_spec_table(domvals, data, additional_table)
   1038         ret_data = Table.from_numpy(domain, X=data, Y=additional_table.Y,
   1039                                     metas=additional_table.metas,
-> 1040                                     attributes=additional_table.attributes)
   1041         return ret_data
   1042 

~/Documents/code/Python/orange3/Orange/data/table.py in from_numpy(cls, domain, X, Y, metas, W, attributes, ids)
    565         :return:
    566         """
--> 567         X, Y, W = _check_arrays(X, Y, W, dtype='float64')
    568         metas, = _check_arrays(metas, dtype=object, shape_1=X.shape[0])
    569         ids, = _check_arrays(ids, dtype=int, shape_1=X.shape[0])

~/Documents/code/Python/orange3/Orange/data/table.py in _check_arrays(dtype, shape_1, *arrays)
   1755         else:
   1756             if dtype is not None:
-> 1757                 array = np.asarray(array, dtype=dtype)
   1758             else:
   1759                 array = np.asarray(array)

~/venv/orange/lib/python3.7/site-packages/numpy/core/_asarray.py in asarray(a, dtype, order)
     81 
     82     """
---> 83     return array(a, dtype, copy=False, order=order)
     84 
     85 

ValueError: setting an array element with a sequence.
```

**Comment by markotoplak** [comment]
Is your environment the same (same packages)? To confirm, could you also try doing the same in Python Script widget?

If it is the same, the difference might have something to do with the sheet option.

**Comment by borondics** [comment]
It was the same virtual environment and the Python Script widget gives a similar error.

Code:
```
import Orange

from orangecontrib.spectroscopy import data

d = Orange.data.Table('/Users/borondics/single beam 100IR 10Green fast.ptir')
```

Result:
```
Python 3.7.9 (default, Nov 14 2020, 23:05:21) 
[Clang 12.0.0 (clang-1200.0.32.27)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(PythonConsole)
>>> 
Running script:
/Users/borondics/Documents/code/Python/orange-spectroscopy/orangecontrib/spectroscopy/data.py:1391: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  intensities = np.array(intensities)
TypeError: only size-1 arrays can be converted to Python scalars

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "<string>", line 5, in <module>
  File "/Users/borondics/Documents/code/Python/orange3/Orange/data/table.py", line 241, in __new__
    return cls.from_file(args[0], **kwargs)
  File "/Users/borondics/Documents/code/Python/orange3/Orange/data/table.py", line 693, in from_file
    data = reader.read()
  File "/Users/borondics/Documents/code/Python/orange-spectroscopy/orangecontrib/spectroscopy/data.py", line 39, in read
    return build_spec_table(*self.read_spectra())
  File "/Users/borondics/Documents/code/Python/orange-spectroscopy/orangecontrib/spectroscopy/data.py", line 1040, in build_spec_table
    attributes=additional_table.attributes)
  File "/Users/borondics/Documents/code/Python/orange3/Orange/data/table.py", line 567, in from_numpy
    X, Y, W = _check_arrays(X, Y, W, dtype='float64')
  File "/Users/borondics/Documents/code/Python/orange3/Orange/data/table.py", line 1757, in _check_arrays
    array = np.asarray(array, dtype=dtype)
  File "/Users/borondics/venv/orange/lib/python3.7/site-packages/numpy/core/_asarray.py", line 83, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: setting an array element with a sequence.
```

**Comment by borondics** [comment]
This error seems to be a lucky coincidence. 

All other files in this measurement sequence worked both from ipython using `Orange.data.Table` and the GUI. However, when testing that particular file with Quasar I didn't pay attention to selecting the same file. In fact, if I try the same file with the GUI it gives the same error as with using the `Python Script` widget and the three lines of code to get the data. 

However, I can open the file with `h5py` and also with `silx` for example.

The reason might be that I manually stopped the acquisition and therefore the last HDF5 entry contains no data, which means that we would need to check in the PTIR reader to have a meaningful number (more than 0) of spectral data points for each HDF5 entry. This might make it an easy fix.
