### ISSUE TITLE
Error on attempting to alter parameters in PeakFit Widget

### ISSUE THREAD

**Issue by bluewin4** [Quasars/orange-spectroscopy#619]
When I attempt to use the peakfit widget I get this error and can no longer alter the peakfitting parameters, it will simply act as though  had the original parameters prior to alteration. 

Here's the workflow and a dataset to reproduce it with.
[Projects.zip](https://github.com/Quasars/orange-spectroscopy/files/9271532/Projects.zip)

![image](https://user-images.githubusercontent.com/47462814/183157964-ce69d847-71b8-4fc9-a93b-c21ae85ae03d.png)

**Comment by bluewin4** [comment]
When I tried to click on a datatable after this I got an empty table and an error


Exception:
ValueError: '399.415039' is not in domain
Module:
Orange.data.domain:345
Version:
3.31.0
Environment:
Python 3.8.8 on Windows 10 10.0.19041 AMD64
Installed Packages:
AnyQt==0.0.13, Bottleneck==1.3.2, CacheControl==0.12.10, Orange-Spectroscopy==0.6.1, Orange3-Explain==0.4.2, Orange3-ImageAnalytics==0.6.0, Orange3-Timeseries==0.3.12, Orange3==3.31.0, Pillow==8.4.0, PyQt5-sip==4.19.18, PyQt5==5.12.3, PyQtChart==5.12, PyQtWebEngine==5.12.1, PySocks==1.7.1, PyWavelets==1.2.0, PyYAML==6.0, Pygments==2.10.0, QtPy==1.11.3, XlsxWriter==3.0.2, anyio==3.4.0, asteval==0.9.25, backcall==0.2.0, backports.functools-lru-cache==1.6.4, baycomp==1.0.2, brotlipy==0.7.0, catboost==1.0.3, certifi==2021.10.8, cffi==1.15.0, chardet==4.0.0, charset-normalizer==2.0.9, cloudpickle==2.0.0, colorama==0.4.4, colorcet==2.0.6, commonmark==0.9.1, cryptography==36.0.1, cycler==0.11.0, cytoolz==0.11.2, dask==2021.11.2, debugpy==1.5.1, decorator==5.1.0, dictdiffer==0.9.0, docutils==0.18.1, entrypoints==0.3, et-xmlfile==1.0.1, extranormal3==0.0.3, fonttools==4.28.5, fsspec==2021.11.1, future==0.18.2, h11==0.12.0, h2==4.1.0, h5py==3.6.0, hpack==4.0.0, httpcore==0.13.7, httpx==0.19.0, hyperframe==6.0.1, idna==3.1, imagecodecs==2021.11.20, imageio==2.13.3, importlib-metadata==4.10.0, ipykernel==6.5.1, ipython-genutils==0.2.0, ipython==7.30.1, jedi==0.18.1, joblib==1.1.0, jupyter-client==7.1.0, jupyter-core==4.9.1, keyring==23.4.0, keyrings.alt==4.0.2, kiwisolver==1.3.2, llvmlite==0.37.0, lmfit==1.0.3, locket==0.2.0, lockfile==0.12.2, matplotlib-inline==0.1.3, matplotlib==3.5.1, more-itertools==8.12.0, msgpack==1.0.3, munkres==1.1.4, ndf==0.1.4, nest-asyncio==1.5.4, networkx==2.6.3, numba==0.54.1, numpy==1.19.5, olefile==0.46, openTSNE==0.6.1, openpyxl==3.0.9, orange-canvas-core==0.1.24, orange-widget-base==4.16.1, packaging==21.3, pandas==1.3.5, param==1.12.0, parso==0.8.3, partd==1.2.0, patsy==0.5.2, pickleshare==0.7.5, pip==21.3.1, prompt-toolkit==3.0.24, pyOpenSSL==21.0.0, pycparser==2.21, pyct==0.4.8, pyparsing==3.0.6, pyqtgraph==0.12.3, python-dateutil==2.8.2, python-louvain==0.15, pytz==2021.3, pywin32-ctypes==0.2.0, pywin32==302, pyzmq==22.3.0, qasync==0.22.0, qtconsole==5.2.2, renishawWiRE==0.1.15, requests==2.26.0, rfc3986==1.5.0, scikit-image==0.19.0, scikit-learn==0.23.2, scipy==1.5.3, serverfiles==0.3.0, setuptools==59.6.0, shap==0.37.0, six==1.16.0, slicer==0.0.7, sniffio==1.2.0, spectral==0.22.4, statsmodels==0.12.1, threadpoolctl==3.0.0, tifffile==2021.11.2, toolz==0.11.2, tornado==6.1, tqdm==4.62.3, traitlets==5.1.1, typing-extensions==4.0.1, uncertainties==3.1.6, unicodedata2==13.0.0.post2, urllib3==1.26.7, wcwidth==0.2.5, wheel==0.37.0, win-inet-pton==1.1.0, xlrd==2.0.1, zipp==3.6.0
Machine ID:
69e6254d-0033-42f9-b11a-a8c09a608043
Stack Trace:
Traceback (most recent call last):
  File "C:\Users\Jack\AppData\Local\Programs\Orange\lib\site-packages\orangewidget\utils\itemdelegates.py", line 112, in itemData
    item = self.__cache_data[key]
  File "C:\Users\Jack\AppData\Local\Programs\Orange\lib\site-packages\orangewidget\utils\cache.py", line 32, in __getitem__
    r = dict_[key]
KeyError: <PyQt5.QtCore.QPersistentModelIndex object at 0x00000288ECF3AF20>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jack\AppData\Local\Programs\Orange\lib\site-packages\orangewidget\utils\itemdelegates.py", line 410, in paint
    self.initStyleOption(opt, index)
  File "C:\Users\Jack\AppData\Local\Programs\Orange\lib\site-packages\orangewidget\utils\itemdelegates.py", line 396, in initStyleOption
    data = self.cachedItemData(index, self.roles)
  File "C:\Users\Jack\AppData\Local\Programs\Orange\lib\site-packages\orangewidget\utils\itemdelegates.py", line 287, in cachedItemData
    return self.__cache.itemData(index, roles)
  File "C:\Users\Jack\AppData\Local\Programs\Orange\lib\site-packages\orangewidget\utils\itemdelegates.py", line 114, in itemData
    data = item_data(index, roles)
  File "C:\Users\Jack\AppData\Local\Programs\Orange\lib\site-packages\orangewidget\utils\itemdelegates.py", line 35, in item_data
    return dict(zip(roles, values))
  File "C:\Users\Jack\AppData\Local\Programs\Orange\lib\site-packages\Orange\widgets\data\owtable.py", line 87, in data
    return super().data(index, role)
  File "C:\Users\Jack\AppData\Local\Programs\Orange\lib\site-packages\Orange\widgets\utils\itemmodels.py", line 983, in data
    return coldesc.format(instance)
  File "C:\Users\Jack\AppData\Local\Programs\Orange\lib\site-packages\Orange\widgets\utils\itemmodels.py", line 833, in format_dense
    return str(instance[var])
  File "C:\Users\Jack\AppData\Local\Programs\Orange\lib\site-packages\Orange\data\instance.py", line 116, in __getitem__
    idx = key if isinstance(key, Integral) else self._domain.index(key)
  File "C:\Users\Jack\AppData\Local\Programs\Orange\lib\site-packages\Orange\data\domain.py", line 345, in index
    raise ValueError("'%s' is not in domain" % var)
ValueError: '399.415039' is not in domain

Local Variables:
OrderedDict([('equiv', None),
             ('idx', None),
             ('self',
              [399.415039, 398.145508, 396.875977, 395.606445, 394.335938, 393.065430, 391.794922, 390.523438, 389.251953, 387.980469, 386.708008, 385.436523, 384.164063, 382.890625, 381.618164, 380.344727, 379.071289, 377.796875, 376.523438, 375.249023, 373.973633, 372.699219, 371.423828, 370.148438, 368.873047, 367.596680, 366.320313, 365.043945, 363.766602, 362.490234, 361.212891, 359.934570, 358.657227, 357.378906, 356.100586, 354.821289, 353.541992, 352.262695, 350.983398, 349.703125, 348.423828, 347.142578, 345.862305, 344.581055, 343.299805, 342.018555, 340.736328, 339.455078, 338.171875, 336.889648, 335.606445, 334.323242, 333.040039, 331.755859, 330.472656, 329.188477, 327.903320, 326.618164, 325.333008, 324.047852, 322.762695, 321.476563, 320.190430, 318.903320, 317.617188, 316.330078, 315.041992, 313.754883, 312.466797, 311.178711, 309.889648, 308.601563, 307.312500, 306.022461, 304.733398, 303.443359, 302.153320, 300.862305, 299.572266, 298.281250, 296.989258, 295.698242, 294.406250, 293.114258, 291.821289, 290.529297, 289.236328, 287.942383, 286.649414, 285.355469, 284.061523, 282.766602, 281.471680, 280.176758, 278.881836, 277.585938, 276.291016, 274.994141, 273.698242, 272.401367, 271.104492, 269.807617, 268.509766, 267.211914, 265.914063, 264.615234, 263.316406, 262.017578, 260.718750, 259.418945, 258.119141, 256.819336, 255.518555, 254.217773, 252.916992, 251.616211, 250.314453, 249.012695, 247.710938, 246.408203, 245.105469, 243.802734, 242.499023, 241.196289, Max, Min] {Filename}),
             ('var',
              ContinuousVariable(name='399.415039', number_of_decimals=3, compute_value=<orangecontrib.spectroscopy.preprocess.SavitzkyGolayFeature object at 0x00000288EA378E20>))])

**Comment by bluewin4** [comment]
Added note: It uninstalled the spectroscopy add on after I had this error and Orange crashed.

**Comment by stuart-cls** [comment]
@bluewin4 Thanks for your report. 

I'm not able to reproduce the error on my Windows machine with Quasar 1.5.0. What parameter did you try to change?

I'm curious what the function of the series of Transpose / Feature Construct / Select / Transpose widgets is. It seems to be functioning as a Cut to reduce the energy range?

Final unsolicited comment, your "Min and Max" script is directly modifying the data table, and so the edit propagates both downstream _and_ upstream. You need to create a copy of the Table before editing it. I don't think this is propagating all the way back up to the Peak Fit widget however, as "Preprocess Spectra (1)" blocks it.

**Comment by bluewin4** [comment]
![image](https://user-images.githubusercontent.com/47462814/188638685-9ff59477-f2b7-4cb2-a2c9-2ef49b6f89c6.png)
[orange_spectroscopy_proble.zip](https://github.com/Quasars/orange-spectroscopy/files/9497004/orange_spectroscopy_proble.zip)


thanks for getting back to me, I thought I had responded but realize now I'd been neglectful! So sorry. 

The parameter I tried to change was the delta on the center this time. I highlight the number, in this case "5" and try to type in "10" which prompts the error to start. As curve fitting is a bit of an art this is a problem in the long run for fitting lots of complex protein spectra.

 It appears to be more likely to occur after I have set up the parameters, closed, and reopened the workflow. 

This has been a persistent problem I've been facing and I'm unsure how to deal with it in the long run. I was more careful in pruning this workflow so you don't have to deal with my cursed arrangements haha. The Transpose/Feature construct/select/transpose is indeed functioning as a Cut. The reason being that Orange seems to have some difficulty keeping track of the wavenumbers through a transpose without me explicitly defining them using a feature constructor.
