### ISSUE TITLE
Multifile different size bug

### ISSUE THREAD

**Issue by borondics** [Quasars/orange-spectroscopy#659]
If there are multiple files read with multifile and they are not the same length / number of points, the widget crashes and doesn't give a meaningful Error message.

**Comment by markotoplak** [comment]
The problem: ```Traceback (most recent call last):
  File "/home/marko/dev/orange-spectroscopy/orangecontrib/spectroscopy/tests/test_owmultifile.py", line 222, in test_spectra_almost_same_wavenumbers
    self.load_files("sample1.spa", "sample1.spa")
  File "/home/marko/dev/orange-spectroscopy/orangecontrib/spectroscopy/tests/test_owmultifile.py", line 65, in load_files
    self.widget.browse_files()
  File "/home/marko/dev/orange-spectroscopy/orangecontrib/spectroscopy/widgets/owmultifile.py", line 373, in browse_files
    self.load_files(filenames, reader)
  File "/home/marko/dev/orange-spectroscopy/orangecontrib/spectroscopy/widgets/owmultifile.py", line 384, in load_files
    self.load_data()
  File "/home/marko/dev/orange-spectroscopy/orangecontrib/spectroscopy/widgets/owmultifile.py", line 445, in load_data
    data = concatenate_data(data_list, fnok_list, self.label)
  File "/home/marko/dev/orange-spectroscopy/orangecontrib/spectroscopy/widgets/owmultifile.py", line 60, in concatenate_data
    spectral_specific_domains = [Domain(attrs, None, None)]
  File "/home/marko/dev/orange3/Orange/data/domain.py", line 154, in __init__
    raise Exception('All variables in the domain should have'
Exception: All variables in the domain should have unique names.
```
